swagger: '2.0'
info:
  version: 1.0.0
  title: resume-api "It Worked"
  description: API for updating visitor count
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /UpdateVisitorCount:
    post:
      summary: Update visitor count
      operationId: updateVisitorCount
      parameters:
        - name: visitorName
          in: body
          required: true
          schema:
            type: object
            properties:
              visitorName:
                type: string
                example: "John"
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              visitorCount:
                type: integer
                example: 42
        '400':
          description: Invalid request body
      x-google-backend:
        address: https://us-west2-infra-earth-377823.cloudfunctions.net/UpdateVisitorCountPOST


