swagger: '2.0'
info:
  title: resume-api
  description: API for updating visitor count
  version: 1.0.0
schemes:
  - https
host: us-west2-infra-earth-377823.cloudfunctions.net
basePath: /
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
paths:
  /UpdateVisitorCount:
    get:
      summary: Get visitor count
      operationId: getVisitorCount
      responses:
        '200':
          description: Successful response
          schema:
            type: integer
        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              error:
                type: string
                example: Failed to retrieve visitor count
      x-google-backend:
        address: https://us-west2-infra-earth-377823.cloudfunctions.net
        path_translation: APPEND_PATH_TO_ADDRESS
