swagger: '2.0'
info:
  title: resume-api
  description: API for updating visitor count
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /UpdateVisitorCount:
    options:
      summary: CORS support
      description: Enable CORS by returning correct headers
      operationId: corsOptions
      responses:
        '200':
          description: Valid preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
        default:
          description: Invalid preflight response
      consumes:
        - application/json
      produces:
        - application/json
    post:
      summary: Update visitor count
      operationId: updateVisitorCount
      x-google-backend:
        address: https://us-west2-infra-earth-377823.cloudfunctions.net/UpdateVisitorCount
      responses:
        '200':
          description: Successful response
          schema:
            type: integer
        '400':
          description: Invalid input data
          schema:
            type: object
            properties:
              error:
                type: string
                example: Invalid count value
        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              error:
                type: string
                example: Failed to update visitor count
      consumes:
        - application/json
      parameters:
        - name: count
          in: body
          required: true
          schema:
            type: integer
            example: 42